# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b920502ca2b97d29121d5e3cf615ac712499c6a534764319657eb3bd4bcf62267a86191d1d410bc2deb018e3023b0f07ca2c4e43d8124d60284e822ebc832a00

test:
  secret_key_base: 8dccf5e05495e7fe5a2c42426817195b387da9ed173a8893d3e2a0bdf17447ac49840d1f752f5e8bd767c1833767423a3a772ec7ef9de3d532023c6e2bd59ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
